### ISSUE TITLE
랜덤 맛집 추천 버튼 구현

### ISSUE THREAD

**Issue by metacode22** [prgrms-web-devcourse/Team-DarkNight-Kkini-FE#15]
## 📕 작업 설명

> 랜덤 맛집 추천 버튼을 누르면 주변 맛집 1개를 추천하는 UI를 띄운다.

## 📖 To-Do list

- [x] Kakao/Google API와 geolocation API를 통해 사용자의 현재 위치를 기반으로 하나의 맛집을 랜덤으로 추천.
- [x] 해당 맛집에 맛집 뱃지 띄우기.
- [x] 맛집 뱃지 클릭 시 해당 맛집에 대한 정보를 모달로 띄우기.
- [x] 모달에서 밥모임 참여하기 버튼 구현.
  - 클릭 시 해당 맛집에 대한 밥모임 리스트 페이지로 이동.

**Comment by live-small** [comment]
@metacode22 이 이슈 클로즈 해도 되지않나요?
