### ISSUE TITLE
header 관련 리팩토링 

### ISSUE THREAD

**Issue by live-small** [prgrms-web-devcourse/Team-DarkNight-Kkini-FE#188]
## 📕 작업 설명

> header 버그 대응 

## 📖 To-Do list

- [x] header 로고 크기 수정 
- [x] header 작은 화면일 때, 닉네임 깨지는 거 대응 
- [x] 이름 변경 시, 바뀐 이름 반영 안되는 버그 수정
