### ISSUE TITLE
채팅 response 수정 

### ISSUE THREAD

**Issue by live-small** [prgrms-web-devcourse/Team-DarkNight-Kkini-FE#222]
## 📕 작업 배경
- 현재 채팅은 서버 측에서 메시지 하나하나에 프로필 이미지랑 이름을 같이 보내고 있음. 
- 서버 측에서는 아이디, 메시지 내역만 보내고, 프론트에서 프로필 이미지, 유저이름 처리하도록 수정하기로 협의함. 

## 작업 설명
user data에 프로필 이미지, 유저이름 데이터가 있기에 그걸 재사용하는 방향으로 수정해야함 

## 📖 To-Do list

- [x] 채팅 코드 파악 
- [x] 채팅 response type 변경 -> response는 7/13일 전체회의에서 협의하기로 함 
- [x] profile image, username 연결

**Comment by live-small** [comment]
- MessageListItem.tsx에서 message.profileImgUrl 부분 바꾸기
