### ISSUE TITLE
globalStyle, style 변수 emotion -> chakra로 관리 

### ISSUE THREAD

**Issue by live-small** [prgrms-web-devcourse/Team-DarkNight-Kkini-FE#34]
## 📕 작업 설명

> emotion으로 관리하던 스타일 세팅을 chakra로 관리

why ? 
- chakra 태그를 이용해 바로 스타일을 적용하는데, emotion에 설정해둔 theme를 쓰기위해 별도의 과정이 필요함 
- chakra 태그에도, emotion에도 스타일 파일이 혼재되어 존재함

## 📖 To-Do list

- [ ] globalStyle -> emotion으로 관리
- [x] style 변수 
- [x] emotion -> chakra로 바꾸기 
- [x] 사용방법 pr에 적기
