### ISSUE TITLE
밥모임 검색 모달 디자인 수정 

### ISSUE THREAD

**Issue by SDWoo** [prgrms-web-devcourse/Team-DarkNight-Kkini-FE#74]
## 📕 작업 설명

> 작업내용

작업 브랜치:

## 📖 To-Do list

- [ ] 공통 버튼 + 차크라 테마로 버튼 작업
- [ ] overflow-x 
- [ ] 좀 더 잘보이게 색상 변경
- [ ] 로딩, 에러 처리
- [ ] placeUrl 추가
