### ISSUE TITLE
밥모임 생성 페이지 추상화

### ISSUE THREAD

**Issue by SDWoo** [prgrms-web-devcourse/Team-DarkNight-Kkini-FE#94]
## 📕 작업 설명

> 밥모임 생성 페이지 추상화

## 📖 To-Do list

- [ ] 밥모임 생성 페이지 추상화
- [ ] 밥모임 생성 버튼 absolute 풀기
- [ ] Accordion 좀 더 잘 사용해보기
- [ ] 선택한 가게명 보여주기
- [ ] 로딩 시 스켈레톤 보여주기
